/** Canonicalize a Ghana phone number to 0XXXXXXXXX format. Returns null if invalid. */
export function normalizeGhanaPhone(input: string): string | null {
  if (!input) return null;
  const s = input.trim().replace(/[\s\-()]/g, "");
  if (/^\+233\d{9}$/.test(s)) return "0" + s.slice(4);
  if (/^233\d{9}$/.test(s)) return "0" + s.slice(3);
  if (/^0\d{9}$/.test(s)) return s;
  return null;
}

/** Simple detector: does this look like an email (contains "@")? */
export function looksLikeEmail(v: string): boolean {
  return /@/.test(v.trim());
}

/** Synthetic email used when a customer registers with phone only. */
export function syntheticEmailForPhone(phone: string): string {
  const canonical = normalizeGhanaPhone(phone) ?? phone.replace(/\D/g, "");
  return `phone.${canonical}@phone.brownsfoods.local`;
}

/** True when an email was generated by us for a phone-only signup. */
export function isSyntheticEmail(email: string | null | undefined): boolean {
  return !!email && email.endsWith("@phone.brownsfoods.local");
}
